apiVersion: v1
kind: Pod
metadata:
  name: app-vitao
  labels:
    env: dev
spec:
  containers:
    - name: app
      image: erichegt/hello-istio:0.1
      env:
        - name: POD_NAME
          value: dev-maroto
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: app-vitao-2
  labels:
    env: dev
spec:
  containers:
    - name: app
      image: erichegt/hello-istio:0.1
      env:
        - name: POD_NAME
          value: dev-maroto-2
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP
