# CUIDADO: as imagens rodadas aqui são da aplicação do repositório do Erich
# https://github.com/erichegt/workshop-k8s-helm-istio

apiVersion: v1
kind: ReplicationController
metadata:
  name: app-vitao
  labels:
    app: app-vitao
spec:
  replicas: 3
  selector:
    rc: app-vitao
  template:
    metadata:
      labels:
        env: dev
        app: app-vitao
        svc: app-vitao
        rc: app-vitao
    spec:
      containers:
        - name: app
          image: erichegt/hello-istio:0.1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # downward API
            - name: POD_PORT
              value: "3000"
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /chain
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: app-vitao-svc
  labels:
    app: app-vitao
spec:
  selector:
    svc: app-vitao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
