version: '2.4'

services:
  maroto_app:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/opt/app_maroto/src
    ports:
      - '3000:3000'
  #   depends_on:
  #     - db
  #     - redis
  # redis:
  #   image: redis
  # db:
  #   image: postgres


# docker build -f Dockerfile --target dev -t maroto_app_dev:-1.1 .
# docker run --rm -p 3000:3000 --name maroto_app -v $(pwd)/src:/opt/app_maroto/src  maroto_app_dev:0.1
