# CUIDADO: as imagens rodadas aqui são da aplicação do repositório do Erich
# https://github.com/erichegt/workshop-k8s-helm-istio

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-vitao-blue
  labels:
    app: app-vitao
spec:
  replicas: 2
  selector:
    matchLabels:
      rs: app-vitao-blue
  template:
    metadata:
      labels:
        env: dev
        app: app-vitao
        svc: app-vitao
        rs: app-vitao-blue
    spec:
      containers:
        - name: app
          image: erichegt/hello-istio:0.1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # downward API
            - name: POD_PORT
              value: '3000'
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /chain
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: app-vitao
  labels:
    env: dev
    app: app-vitao
spec:
  selector:
    svc: app-vitao
    rs: app-vitao-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-vitao-green
  labels:
    app: app-vitao
spec:
  replicas: 2
  selector:
    matchLabels:
      rs: app-vitao-green
  template:
    metadata:
      labels:
        env: dev
        app: app-vitao
        rs: app-vitao-green
        svc: app-vitao
    spec:
      containers:
        - name: app
          image: erichegt/hello-istio:0.2
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #downward API
            - name: POD_PORT
              value: '3000'
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /chain
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
